### ISSUE TITLE
empty build.cmd should ask for FAKE path or executable

### ISSUE THREAD

**Issue by pr-yemibedu** [ionide/ionide-atom-fake#13]
Hello,
 I was working with vscode with ionide and switched to atom to build the project. Initially it did not have a build.cmd file (task.json was used to find FAKE). An empty build.cmd was made to start. The build crash resulted from just hitting f5.

The user should know that you are looking for FAKE to spawn by path and explain where it is currently looking, tell them that nothing can be built and not actually crash. Thank you. Good day.

[Enter steps to reproduce below:]

1. ... make an empty build.cmd file in a project
2. ... press f5 to build

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 10 Home
**Thrown From**: [ionide-fake](https://github.com/Ionide/ionide-fake) package, v1.2.2

### Stack Trace

Uncaught Error: spawn UNKNOWN

```
At internal/child_process.js:302

Error: spawn UNKNOWN
    at exports._errnoException (util.js:890:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at Object.exports.spawn (child_process.js:379:9)
    at Process__spawnWithNotifications$ (C:\Users\PREmployee\.atom\packages\ionide-fake\lib\fake.js:958:29)
    at FakeService__startBuild$ (C:\Users\PREmployee\.atom\packages\ionide-fake\lib\fake.js:584:23)
    at FakeService__BuildDefault$ (C:\Users\PREmployee\.atom\packages\ionide-fake\lib\fake.js:219:14)
    at atom-workspace.<anonymous> (C:\Users\PREmployee\.atom\packages\ionide-fake\lib\fake.js:340:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\PREmployee\AppData\Local\atom\app-1.10.2\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\PREmployee\AppData\Local\atom\app-1.10.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\PREmployee\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\PREmployee\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\PREmployee\AppData\Local\atom\app-1.10.2\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\PREmployee\AppData\Local\atom\app-1.10.2\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -0:19.6.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:15.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.4.0 FAKE:Build-Default (atom-text-editor.editor.is-focused)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.16.4 (inactive)
atom-yeoman, v0.3.15 (active)
ionide-fake, v1.2.2 (active)
ionide-fsharp, v1.9.1 (active)
ionide-fsi, v2.1.3 (active)
ionide-installer, v1.3.0 (active)
ionide-paket, v2.2.6 (active)
ionide-webview, v1.0.3 (active)
ionide-yeoman, v1.0.2 (active)
linter, v1.11.16 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by pr-yemibedu** [comment]
Hello,
 In my case the easiest way to make it work was to add "packages/FAKE/tools/FAKE.exe" into the build.cmd file with nothing else since it was already working through VSCode. maybe that could be added to the error message as an example to the user. Thank you. Good day.
